### ISSUE TITLE
Klon osoby nie zawiera klona adresu a jego dowiązanie do adresu osoby klonowanej

### ISSUE THREAD

**Issue by famo08** [pomykalskimateusz/project_1_stringi#2]

**Comment by pomykalskimateusz** [comment]
Poprawione, powinno działać ;)

**Comment by famo08** [comment]
jest ok.
Sprawdzanie czy ulica nie jest nullem nie jest konieczne> bez tego wpisałbyś po prostu nulla, co w niczym by nie szkodziło.
Za to jeśli robisz już takie sprawdzenie ładniej byłoby w klasie adres zrobić metodę mówiącą true/false,czy uliza występuję (np: public boolean adresPosiadaUlice() )
